meta_product_name: "Plantyy"
meta_title: "Plantyy - Happy plants, happy people"
meta_description: "Always wanted to have a green garden, balkony or just living room but you don't know what to do? Don't worry, you have Plantyy!"
twitter_account: "@product_twitter_account"   # required for Twitter Cards
